apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mmur
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dial-tenant/rhtap-demo-app/hacbs-test-project-mmur@sha256:2404ca304725c587a0533b91f0120b1998139b2d963c3f78d192160ee872d31d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
